CREATE TABLE DanhMuc (
    id SERIAL PRIMARY KEY,
    ma_danh_muc VARCHAR(10) NOT NULL UNIQUE,
    ten_danh_muc VARCHAR(100) NOT NULL UNIQUE,
    mo_ta TEXT NULL,
    ngay_tao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);